---
note: ""
label: ""
description: ""
parameters:
  datasetIds:
    defaultValue: ["progenetix"]
    isMulti: true
  cohorts: # TODO
    placeholder: ""
    isHidden: false
  assemblyId:
    defaultValue: "GRCh38"
    isHidden: true
  geneId:
    placeholder: ""
  referenceName:
    placeholder: "9"
  start:
    placeholder: "19000001-21975098"
  end:
    placeholder: "21967753-24000000"
  variantType:
    placeholder: "EFO:0030067"
  alternateBases:
    placeholder: "N"
    isHidden: true
  referenceBases:
    placeholder: ""
    isHidden: true
  accessid:
    isHidden: true
