---
datasetIds:
  label: Dataset
  isMulti: true
  rules:
    required: true
  defaultValue: ["progenetix"]
  options:
    - value: progenetix
      label: Progenetix
    - value: cellz
      label: Cancer Cell Lines Collection
    - value: examplez
      label: Test Database - examplez
assemblyId:
  label: Genome Assembly
  infoText: |
    The genome reference assembly.
  defaultValue: GRCh38
  options:
    - value: GRCh38
      label: GRCh38 / hg38
geneId:
  label: Gene Symbol
  infoText: The gene symbol (HUGO).
referenceName:
  label: Chromosome
  infoText: The chromosome with the variant(s).
  placeholder: "refseq:NC_000009.12"
  options:
    - label: "NC_000001.11"
      value: "refseq:NC_000001.11"
    - label: "NC_000002.12"
      value: "refseq:NC_000002.12"
    - label: "NC_000003.12"
      value: "refseq:NC_000003.12"
    - label: "NC_000004.12"
      value: "refseq:NC_000004.12"
    - label: "NC_000005.10"
      value: "refseq:NC_000005.10"
    - label: "NC_000006.12"
      value: "refseq:NC_000006.12"
    - label: "NC_000007.14"
      value: "refseq:NC_000007.14"
    - label: "NC_000008.11"
      value: "refseq:NC_000008.11"
    - label: "NC_000009.12"
      value: "refseq:NC_000009.12"
    - label: "NC_000010.11"
      value: "refseq:NC_000010.11"
    - label: "NC_000011.10"
      value: "refseq:NC_000011.10"
    - label: "NC_000012.12"
      value: "refseq:NC_000012.12"
    - label: "NC_000013.11"
      value: "refseq:NC_000013.11"
    - label: "NC_000014.9"
      value: "refseq:NC_000014.9"
    - label: "NC_000015.10"
      value: "refseq:NC_000015.10"
    - label: "NC_000016.10"
      value: "refseq:NC_000016.10"
    - label: "NC_000017.11"
      value: "refseq:NC_000017.11"
    - label: "NC_000018.10"
      value: "refseq:NC_000018.10"
    - label: "NC_000019.10"
      value: "refseq:NC_000019.10"
    - label: "NC_000020.11"
      value: "refseq:NC_000020.11"
    - label: "NC_000021.9"
      value: "refseq:NC_000021.9"
    - label: "NC_000022.11"
      value: "refseq:NC_000022.11"
    - label: "NC_000023.11 (X)"
      value: "refseq:NC_000023.11"
    - label: "NC_000024.10 (Y)"
      value: "refseq:NC_000024.10"
variantType:
  label: "Variant Type"
  infoText: >-
    The type of a structural variant for e.g. CNV searches.
  defaultValue: ""
  options:
    - value: ""
      label: ""
    - value: "EFO:0030067"
      label: "EFO:0030067 (copy number deletion)"
    - value: "EFO:0030070"
      label: "EFO:0030070 (copy number gain)"
    - value: "EFO:0030066"
      label: "EFO:0030066 (any relative CN variation)"
    - value: "SO:0001059"
      label: "SO:0001059 (any sequence alteration - SNV, INDEL...)"
start:
  label: Start or Position
  infoText: |
    The 1-based genomic position of the variant, or the start of a range query,
    specified through a single value.
    However, in case of fuzzy requests for e.g. copy number variants, the start
    position will usually be provided as a range for the possible occurrence of
    the CNV start (e.g. "21500001-21975098").
end:
  label: End (Range or Structural Var.)
  infoText: |
    The 1-based genomic end position of a range query, specified through a
    single value, or in case of fuzzy requests for e.g. copy number variants
    the end provided as a range for the possible occurrence of
    the CNV end (e.g. "21967753-22500000").
variantMinLength:
  label: Minimum Variant Length
  type: number
  infoText: The minimal length, in bases, of a genomic variant. This parameter can be applied to e.g. CNV queries.
variantMaxLength:
  label: Maximal Variant Length
  type: number
  infoText: The maximal length, in bases, of a genomic variant. This parameter can be applied to e.g. CNV queries.
referenceBases:
  label: Reference Base(s)
alternateBases:
  label: Alternate Base(s)
cohorts:
  label: Cohorts
  infoText: >
    An aggregation of samples by origin (e.g. study, external resource), shared features or use in a publication.
  rules:
    required: false
  defaultValue: ""
  # options:
  #   - value: ""
  #     label: "(no selection)"
  #   - value: pgx:cohort-arraymap
  #     label: arrayMap Samples
bioontology:
  label: Cancer Classification(s)
  infoLink: "https://info.progenetix.org/doc/filters-documentation.html"
  infoText: |
    Special filter type for disease classification codes. If using multiple
    codes please be aware that probably use of an "OR" filter logic will be appropriate.
  isMulti: true
  options:
    - value: ""
      label: "(no selection)"
referenceid:
  label: Reference ID(s)
  infoText: |
    Special filter type for external reference codes such as PMIDs or cellosaurus
    id values.
    If using multiple codes please be aware that probably use of an "OR" filter
    logic will be appropriate.
  isMulti: true
  options:
    - value: ""
      label: "(no selection)"
clinicalClasses:
  label: Clinical Classes
  infoText: |
    Clinical and diagnostic support classifications, such as tumor grading or staging.
  isMulti: true
  options:
    - value: ""
      label: "(no selection)"
materialtype:
  label: Biosample Type
  infoText: |
    Special filter type, to e.g. limit responses to neoplastic or reference
    samples, respectively, when not using specific cancer classification codes.
  defaultValue: ""
  options:
    - value: ""
      label: "(no selection)"
    - value: EFO:0009656
      label: neoplastic sample
    - value: EFO:0030035
      label: cancer cell line sample
    - value: EFO:0009654
      label: reference sample
sex:
  label: Genotypic Sex
  infoText: |
    Genotypic sex of the individual.
  defaultValue: ""
  options:
    - value: ""
      label: "(no selection)"
    - value: PATO:0020002
      label: Female genotypic Sex
    - value: PATO:0020001
      label: Male genotypic Sex
freeFilters:
  label: Filters
  infoLink: "https://info.progenetix.org/doc/filters-documentation.html"
  infoText: |
    Add free comma-concatenated **filters** to the search. These will usually
    correspond to CURIE values supported by the resource (e.g.
    "cellosaurus:CVCL_0004"; "NCIT:C3222"; "PMID:18559507"). Please see the 
    Documentation for details.
accessid:
  label: Accession Prefilter
filterLogic:
  label: Filter Logic
  infoText: |
    Boolean logic for filter values; the default **AND** assumes different
    logical scopes for used filters (e.g. collision occurr if multiple cancer
    diagnoses are used with AND). Please be aware that "Filters" here include
    the "Cancer Classification", "Biosample Type" and "Filters" fields.
  defaultValue: "AND"
  options:
    - value: AND
      label: AND
    - value: OR
      label: OR
includeDescendantTerms:
  label: Include Child Terms
  infoText: >-
    As standard, any selected filter will also include matches on its child
    terms; i.e. NCIT:C3052 - Digestive System Neoplasm will include results
    from gastric, esophagus, colon ... cancer. However, this parameter allows
    to limit searches to the exact code match.
  defaultValue: "True"
  options:
    - value: "true"
      label: always match child terms
    - value: "false"
      label: only match exact code(s)
# filterPrecision:
#   label: Filter Precision
#   infoText: |
#     Logic for the matching of filter terms. The use of "start" will e.g.
#     allow to match all "icdom-8500_" values (i.e. ductal breast carcinomas
#     and precursors - "...85000, ...85001, ...85002, ...85003")
#   defaultValue: "exact"
#   options:
#   - value: exact
#     label: Exact term match
#   - value: start
#     label: Start-anchored term match
geoCity:
  label: City
  infoText: |
    Selector for a city for which the samples have been annotated, usually corresponding to origin of the data.
geodistanceKm:
  infoText: |
    Proximity of the data matches to the selected city, to allow for fuzzy
    annotations or large geographic area searches (e.g. "European samples" through
    "Zurich + 2000km").
  label: Range (km)
  type: number
  defaultValue: 100
skip:
  label: Skip Pages
  infoText: >
    The number of result pages to skip when retrieving data.
  rules:
    required: false
  defaultValue: 0
limit:
  label: Response Limit / Page Size
  infoText: >
    The maximum number of biosamples to retrieve per page and also the size of response pages.
  rules:
    required: false
  defaultValue: 1000