---
description: |-
  This file contains examples for the combined display of CNV frequency profiles.

  The example values for the different fields are set in the `defaultValue`
  field of each parameter. The structure is as follows:

  ```
  - label: "Some Label"
    note: Internal note to understand the example.
    description: |
      The description text that will be rendered on the page.
    parameters:
      datasetIds:
        defaultValue:
          - progenetix
          - cellz
      bioontology:
        defaultValue:
          - NCIT:C3512
          - NCIT:C3493
          - NCIT:C4450
          - NCIT:C4917
      plotChros:
        defaultValue: 1,3,5,7,8,11,16,17,20

  ```
examples:
  - label: "Lung Cancers"
    note: "Lung cancers with different histological types"
    description: |
      This example shows CNV frequency profiles for different lung cancer types.
    parameters:
      bioontology:
        defaultValue:
          - NCIT:C3512
          - NCIT:C3493
          - NCIT:C4450
          - NCIT:C4917
  - label: "Breast Cancers and Cell Lines"
    note: "Breast cancers and cell lines"
    description: |
      Breast cancers and cell lines by calling profiles from Progenetix
      and [cancercelllines.org](https://cancercelllines.org/). Note: Progenetix also
      contains a minority subset of cell lines.
    parameters:
      datasetIds:
        defaultValue:
          - progenetix
          - cellz
      bioontology:
        defaultValue:
          - NCIT:C9245
      plotChros:
        defaultValue: 1,3,5,7,8,11,16,17,20
