---
- label: "CDKN2A Deletion Example"
  note: "Example for focal CDKN2A deletion matches."
  description: |
    This example shows the query for CNV deletion variants overlapping the
    CDKN2A gene's coding region with at least a single base, but limited
    to "highly focal" hits (here i.e. <= ~1Mbp in size) in Glioblastoma samples. The query can be modified e.g. through changing the position parameters or diagnosis.
  parameters:
    referenceName:
      defaultValue: "refseq:NC_000009.12"
    start:
      defaultValue: "21500001-21975098"
    end:
      defaultValue: "21967753-22500000"
    variantType:
      defaultValue: "EFO:0030067"
    allTermsFilters:
      defaultValue: ["NCIT:C3058", "pgx:cohort-TCGA"]
      isHidden: false
- label: "MYC Duplication"
  note: "Example for focal MYC Duplications."
  description: |
    The example parameters will select samples with a continuous, focal duplication of the complete MYC coding region. The serarch will be limited to  neoplastic samples (EFO:0009656).
  parameters:
    referenceName:
      defaultValue: "refseq:NC_000008.11"
    start:
      defaultValue: "124000000-127736593"
    end:
      defaultValue: "127740957-130000000"
    variantType:
      defaultValue: "EFO:0030070"
    materialtype:
      defaultValue: "EFO:0009656"
    allTermsFilters:
      defaultValue: ["pgx:cohort-TCGA"]
      isHidden: false
